# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7db9cdb08936b5acd5ac9549f6355f77fd625b2a6fd005aa711bf3f5d85a9d986c68a3280730319d6418752333b0bd1b3303cffc0eb7558624bc139d5de1a2fc

test:
  secret_key_base: d99848478c2cf24d9e6405647224aa7f3377497e49701c6158f2d806afd6158d9b0f04fc667531c723e0e10d07d443ec117a0515641eb0b15de0f0e70c26e5c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
